# image will be published to ghcr.io/<user>/<name>
name: idros-nv470
# description will be included in the image's metadata
description: Containerized OS that suits my workflow. Nvidia variant.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 39-470 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: files.yml
  - from-file: rpms.yml
  - from-file: flatpaks.yml
  - from-file: bling.yml
  - type: yafti
  - type: script
    scripts:
      - signing.sh
