title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to uBlue (Alpha)"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.
    command-drop-down:
      source: yafti.screen.package
      values:
        title: Commands to run
        show_terminal: true
        package_manager: yafti.plugin.run
        groups:
          Mullvad VPN:
            description: Install Mullvad VPN? Restart after installing. Dont forget to run `sudo systemctl enable --now mullvad-daemon` after install
            default: true
            packages:
            - Desktop: |
                wget --content-disposition -nv -P /tmp/rpms https://mullvad.net/download/app/rpm/latest; rpm-ostree install /tmp/rpms/MullvadVPN-*.rpm; rm /tmp/rpms/MullvadVPN-*.rpm
  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome, Traveler!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features. This step will therefore remove all basic Fedora Flatpaks from your system! We will instead switch all core Flatpak applications over to the vastly superior, unfiltered Flathub. If you don't want to do this, simply exit this installer.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
  check-user-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (User)
      condition:
        run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
      actions:
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        Core GNOME Apps:
          description: Core system applications for the GNOME desktop environment.
          default: true
          packages:
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Characters: org.gnome.Characters
            - Cheese: org.gnome.Cheese
            - Clocks: org.gnome.clocks
            - Connections: org.gnome.Connections
            - Contacts: org.gnome.Contacts
            - Disk Usage Analyzer: org.gnome.baobab
            - Document Scanner: org.gnome.SimpleScan
            - Document Viewer: org.gnome.Evince
            - Extension Manager: com.mattjakeman.ExtensionManager
            - Font Viewer: org.gnome.font-viewer
            - Image Viewer: org.gnome.eog
            - Logs: org.gnome.Logs
            - Maps: org.gnome.Maps
            - Photos (Organizer): org.gnome.Photos
            - Sushi (Nautilus Previewer): org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Todo: org.gnome.Todo
            # - Videos (Player): org.gnome.Totem
            - Weather: org.gnome.Weather
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            # - Deja Dup Backups: org.gnome.DejaDup
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Flatseal (Permission Manager): com.github.tchx84.Flatseal
            - Flatsweep: io.github.giantpinkrobots.flatsweep
            # - Font Downloader: org.gustavoperedo.FontDownloader
            # - Mozilla Firefox: org.mozilla.firefox
            - Czkawka: com.github.qarmin.czkawka
            - qBittorrent: org.qbittorrent.qBittorrent
            # - Bleachbit: org.bleachbit.BleachBit
        Web Browsers:
          description: Additional browsers.
          default: true
          packages:
            - Firefox: org.mozilla.firefox
            - Brave: com.brave.Browser
            - Mullvad: net.mullvad.MullvadBrowser
            - Tor Browser: com.github.micahflee.torbrowser-launcher
            # - Google Chrome: com.google.Chrome
            # - Microsoft Edge: com.microsoft.Edge
            # - Opera: com.opera.Opera
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Bottles: com.usebottles.bottles
            - Discord: com.discordapp.Discord
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope
            - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
            - SteamTinkerLaunch (Utility): com.valvesoftware.Steam.Utility.steamtinkerlaunch
            - Proton Updater for Steam: net.davidotek.pupgui2
        Communication:
          description: Tools for communication.
          default: true
          packages:
            # - Slack: com.slack.Slack
            # - Thunderbird Email: org.mozilla.Thunderbird
            - Tutanota (Experimental): com.tutanota.Tutanota
            - Signal Desktop: org.signal.Signal
            # - Element: im.riot.Riot
        Office:
          description: Boost your productivity.
          default: true
          packages:
            # - Syncthing: me.kozec.syncthingtk
            - Nextcloud: com.nextcloud.desktopclient.nextcloud
            - Cryptomator: org.cryptomator.Cryptomator
            # - LibreOffice: org.libreoffice.LibreOffice
            - OnlyOffice: org.onlyoffice.desktopeditors
            # - Obsidian: md.obsidian.Obsidian
            # - Joplin: net.cozic.joplin_desktop
            - Logseq: com.logseq.Logseq
            # - Standard Notes: org.standardnotes.standardnotes
            # - Calibre: com.calibre_ebook.calibre
        Development:
          description: Tools for software development
          default: true
          packages:
            # - VSCode: com.visualstudio.code
            - DBeaver Community: io.dbeaver.DBeaverCommunity
            # - Android Studio: com.google.AndroidStudio
        Media:
          description: Tools for playing and editing media (audio, video, images)
          default: true
          packages:
            - FreeTube: io.freetubeapp.FreeTube
            - VLC media player: org.videolan.VLC
            - Losslesscut: no.mifi.losslesscut
            # - Shortwave: de.haeckerfelix.Shortwave # Internet radio
            # - GIMP: org.gimp.GIMP
            # - OBS Studio: com.obsproject.Studio
        Streaming:
          description: Stream to the Internet.
          default: false
          packages:
            - OBS Studio: com.obsproject.Studio
            - VkCapture for OBS: com.obsproject.Studio.OBSVkCapture
            - Gstreamer for OBS: com.obsproject.Studio.Plugin.Gstreamer
            - Gstreamer VAAPI for OBS: com.obsproject.Studio.Plugin.GStreamerVaapi
            - Boatswain for Streamdeck: com.feaneron.Boatswain
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying uBlue, we hope you enjoy it!
